### ISSUE TITLE
feature for further improvements on SearchView

### ISSUE THREAD

**Issue by Charles-C-Feng** [azyx0083/CSC207-WhatEver-46#15]
As more functions are added, more and more controllers and buttons will be needed in searchView. Currently, the way the view distinguishes controllers is based on the order of parameters. This method performs well when faced with a few limited parameters, but when the scale of the problem increases, relying solely on the order of parameters becomes less reliable, so we decided to make the creation of the controller and ViewModel more automated. This enables SearchView to automatically distinguish controllers and add a button and a controller call corresponding to the button for each controller. The current solution is to first create a FactoryArray in the Factory, and then call the createController method in the Factory to turn the required multiple controllers into one controllerArray. Also add buttonName to ButtonArray in searchViewModel in the same order. Then we can use a for loop to simultaneously traverse the controller and its buttonName and create a JButton to achieve automation.

**Current Problems**

- Since the methods in SingleStockFactory are all static methods, creating an array requires an instance, and an instance cannot call the static method through the dot method. So how to create such an Array becomes a question.

**Comment by azyx0083** [comment]
Issue solved.

All separate parameters are replaced by Maps. Now, the factories and views can use for loops to generate corresponding controllers and buttons for different visualizations. Suppose more ways of visualization (other types of graphical/tabular view of stock) are added in the future. In that case, the factory and OptionsView (previously known as SearchView) don't need to be changed. Only need to adjust the Map in Main and add more button labels in the ViewModel.

See commits a43e1534322dccd1ee427ee8751eb5b13dc59eda and f0265cf2cabfe7cc0d5e73f109004d176b5aa259 for details.
